### ISSUE TITLE
Depth out of bounds

### ISSUE THREAD

**Issue by cqsniha** [kikfox/ARSCTool#3]
As you can see,It can not deal with depth more than 3 levels.
![Uploading 16680055789201194173028405090771.jpg…]()
I: 00.015 Dumping ... 'D:\platform-tools\Java\resources.arsc'
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at com.kikfox.lib.arsc.AItemString.decodeUtf8StringByteLength(AItemString.java:388)
        at com.kikfox.lib.arsc.AItemString.decodeString(AItemString.java:358)
        at com.kikfox.lib.arsc.AItemString.decodeString(AItemString.java:205)
        at com.kikfox.lib.arsc.AItemString.onBytesChanged(AItemString.java:213)
        at com.kikfox.lib.arsc.AItemString.loadBytes(AItemString.java:92)
        at com.kikfox.lib.arsc.ARSCArrayOffsets.loadItemBytes(ARSCArrayOffsets.java:49)
        at com.kikfox.lib.arsc.ARSCBlockArray.loadBytes(ARSCBlockArray.java:31)
        at com.kikfox.lib.arsc.ARSCBlockArray.loadItemBytes(ARSCBlockArray.java:39)
        at com.kikfox.lib.arsc.ARSCBlockArray.loadBytes(ARSCBlockArray.java:31)
        at com.kikfox.lib.arsc.ARSCResource.loadBodyBytes(ARSCResource.java:65)
        at com.kikfox.lib.arsc.ARSCResource.loadItemBytes(ARSCResource.java:56)
        at com.kikfox.lib.arsc.ARSCBlockArray.loadBytes(ARSCBlockArray.java:31)
        at com.kikfox.lib.arsc.ARSCBlockArray.loadItemBytes(ARSCBlockArray.java:39)
        at com.kikfox.lib.arsc.ARSCBlockArray.loadBytes(ARSCBlockArray.java:31)
        at com.kikfox.lib.arsc.ARSCResource.loadBodyBytes(ARSCResource.java:65)
        at com.kikfox.lib.arsc.ARSCResource.loadItemBytes(ARSCResource.java:56)
        at com.kikfox.lib.arsc.ARSCBlockArray.loadBytes(ARSCBlockArray.java:31)
        at com.command.CommandDump.dump(CommandDump.java:35)
        at com.command.CommandDump.run(CommandDump.java:28)
        at com.command.BaseCommand.parse(BaseCommand.java:36)
        at com.command.CommandDump.parse(CommandDump.java:13)
        at com.command.Command.run(Command.java:34)
        at com.kikfox.arscTool.Main.main(Main.java:15)

**Comment by cqsniha** [comment]
Really useful tool!Hope you fix it.Thanks very much

**Comment by REAndroid** [comment]
> Really useful tool!Hope you fix it.Thanks very much

Check this tool:

[https://github.com/REAndroid/APKEditor](https://github.com/REAndroid/APKEditor)

**Comment by cqsniha** [comment]
> > Really useful tool!Hope you fix it.Thanks very much
> 
> Check this tool:
> 
> https://github.com/REAndroid/APKEditor

Thanks!
